config/routes.rb
Agilemetrics::Application.routes.draw do
  devise_for :users

  resources :open_defects

  resources :projects do
    resources :open_defects
  end

  resources :teams do
    resources :sprints
    resources :projects
  end

  match 'averages' => 'teams#averages', :as => "team_averages"
  match 'checklist' => 'checklist#index', :as => "checklist"

  root :to => 'teams#index'

end

app/models/open_defect.rb
class OpenDefect < ActiveRecord::Base
	belongs_to :project
end

app/controllers/open_defects_controller.rb
class OpenDefectsController < ApplicationController


  # GET /open_defects
  # GET /open_defects.json
  def index
    if params[:team_id]
      @team = Team.find(params[:team_id])
      @projects = Project.find(:team_id => @team.id)
    else
      @projects = Project.all
    end

    if params[:project_id]
      @project = Project.find(params[:project_id])
      @team = Team.find(@project.team_id)
    end

    if @project
      @open_defects = @project.open_defects.order("week_ending desc")
    else
      @open_defects = OpenDefect.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @open_defects }
    end
  end



  # GET /open_defects/1
  # GET /open_defects/1.json
  def show
    @open_defect = OpenDefect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @open_defect }
    end
  end



  # GET /open_defects/new
  # GET /open_defects/new.json
  def new
    @open_defect = OpenDefect.new
    @projects = Project.order("name")

    if params[:project_id]
      @project = Project.find(params[:project_id])
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @open_defect }
    end
  end



  # GET /open_defects/1/edit
  def edit
    @open_defect = OpenDefect.find(params[:id])
    @projects = Project.order("name")
    @project = Project.find(@open_defect.project_id)
  end



  # POST /open_defects
  # POST /open_defects.json
  def create
    @open_defect = OpenDefect.new(params[:open_defect])

    respond_to do |format|
      if @open_defect.save
        format.html { redirect_to @open_defect, notice: 'Open defect was successfully created.' }
        format.json { render json: @open_defect, status: :created, location: @open_defect }
      else
        format.html { render action: "new" }
        format.json { render json: @open_defect.errors, status: :unprocessable_entity }
      end
    end
  end



  # PUT /open_defects/1
  # PUT /open_defects/1.json
  def update
    @open_defect = OpenDefect.find(params[:id])

    respond_to do |format|
      if @open_defect.update_attributes(params[:open_defect])
        format.html { redirect_to @open_defect, notice: 'Open defect was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @open_defect.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /open_defects/1
  # DELETE /open_defects/1.json
  def destroy
    @open_defect = OpenDefect.find(params[:id])
    @open_defect.destroy

    respond_to do |format|
      format.html { redirect_to open_defects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/open_defects_helper.rb
module OpenDefectsHelper

  @@OPEN_DEFECTS_REPORT_NUMBER_OF_WEEKS = 52
  @@DEFAULT_SPRINT_WEEKS = 2



  # return all open defects reports for a project up to number (default is 52 weeks)
  def open_defects_for_project(project, number=@@OPEN_DEFECTS_REPORT_NUMBER_OF_WEEKS)
    OpenDefect.where(:project_id => project.id).order("week_ending DESC").limit(number)
  end



  # return only the latest open defects report for a project
  def current_open_defects_for_project(project)
    return OpenDefect.where(:project_id => project.id).order("week_ending DESC").limit(1)
  end



  # return open defects report in a format that the google visualization api can use
  def get_open_defects_data_table(open_defects, sprint_weeks=@@DEFAULT_SPRINT_WEEKS)
    result = []

    headers = ['Week', 'Critical', 'High', 'Medium', 'Low'];
    result.push headers

    @open_defects.reverse_each do |weekly_report|
      data = [
        "Week ending " + weekly_report.week_ending.strftime("%Y.%m.%d"),
        weekly_report.critical,
        weekly_report.high,
        weekly_report.medium,
        weekly_report.low,
      ]

      result.push data
    end

    return result
  end



  # return open defects report in a format that the google visualization api can use
  # filter to show only the report for the last week of the sprint (approximately)
  # change the date displayed from Saturday to Friday
  def get_open_defects_for_sprint_data_table(open_defects, sprint_weeks=@@DEFAULT_SPRINT_WEEKS)
    result = []

    headers = ['Week', 'Critical', 'High', 'Medium', 'Low'];
    result.push headers

    week_number = 0
    @open_defects.reverse_each do |weekly_report|
      data = [
        # change the day displayed from Saturday to Friday
        (weekly_report.week_ending - 24.hours).strftime("%Y.%m.%d"),
        weekly_report.critical,
        weekly_report.high,
        weekly_report.medium,
        weekly_report.low,
      ]

      # only display open defects for the week at the end of each sprint
      # this isn't guaranteed to be accurate because sprint weeks might be off
      if week_number == sprint_weeks
        week_number = 0
        result.push data
      end
      week_number +=1
    end

    return result
  end

end

app/views/open_defects/_form.html.erb
<%= form_for(@open_defect) do |f| %>

  <% if @open_defect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@open_defect.errors.count, "error") %> prohibited this open_defect from being saved:</h2>

      <ul>
      <% @open_defect.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.collection_select :project_id, @projects, :id, :name, :prompt => true, :selected => selected?(@project.id) %>
  </div>
  <div class="field">
    <%= f.label :week_ending %><br />
    <%= f.date_select :week_ending %>
  </div>
  <div class="field">
    <%= f.label :critical %><br />
    <%= f.number_field :critical %>
  </div>
  <div class="field">
    <%= f.label :high %><br />
    <%= f.number_field :high %>
  </div>
  <div class="field">
    <%= f.label :medium %><br />
    <%= f.number_field :medium %>
  </div>
  <div class="field">
    <%= f.label :low %><br />
    <%= f.number_field :low %>
  </div>
  <div class="actions">
    <%= f.submit "save", :class => "button" %>
  </div>
<% end %>

app/views/open_defects/_list.html.erb
<table class="open_defects">

  <thead>
    <tr>
      <th class="open_defects">Project</th>
      <th class="open_defects">Week Ending</th>
      <th class="open_defects">Critical</th>
      <th class="open_defects">High</th>
      <th class="open_defects">Medium</th>
      <th class="open_defects">Low</th>
      <th class="open_defects">Total</th>
      <th class="actions">Actions</th>
    </tr>
  </thead>
  <tbody>

  <% open_defects.each do |week| %>
  <% project = Project.find(week.project_id) %>

    <tr>
      <td class="project"><%= link_to project.name, project_path(project) %></td>
      <td class="week_ending"><%= week.week_ending %></td>
      <td class="defect_count"><%= week.critical %></td>
      <td class="defect_count"><%= week.high %></td>
      <td class="defect_count"><%= week.medium %></td>
      <td class="defect_count"><%= week.low %></td>
      <td class="defect_count"><%= week.low %></td>
      <td class="defect_count defect_total"><%= week.critical + week.high + week.medium + week.low %></td>
      <td class="actions"><%= link_to "edit", edit_open_defect_path(week) %></td>
    </tr>

  <% end %>

  </tbody>
</table>

app/views/open_defects/edit.html.erb
<h1>Edit Open Defects</h1>

<%= render 'form' %>

<%= link_to 'Show', @open_defect %> |
<%= link_to 'Back', open_defects_path %>

app/views/open_defects/index.html.erb
<h1>Open Defects</h1>

<% if @team %>
  <h2>team <%= link_to @team.name, team_path(@team) %> </h2>
<% end %>

<% if @project %>
  <h2>project <%= link_to @project.name, project_path(@project) %> </h2>
<% end %>

<%= render "open_defects/list", :open_defects => @open_defects, :project => @project %>

<br />

<% if is_username_an_owner_of_team?(current_user.login, @team) -%>
  <%= link_to "add open defects", new_project_open_defect_path, :project => @project, :class => "button" %>
<% end %>

app/views/open_defects/new.html.erb
<h1>new open defects report</h1>

<% if @team %>
  <h2> team <%= link_to @team.name, team_path(@team) %> </h2>
<% end %>


<% if @project %>
  <h2> project <%= link_to @project.name, project_path(@project) %> </h2>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', open_defects_path %>

app/views/open_defects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @open_defect.id %>
</p>

<p>
  <b>Week ending:</b>
  <%= @open_defect.week_ending %>
</p>

<p>
  <b>Critical:</b>
  <%= @open_defect.critical %>
</p>

<p>
  <b>High:</b>
  <%= @open_defect.high %>
</p>

<p>
  <b>Medium:</b>
  <%= @open_defect.medium %>
</p>

<p>
  <b>Low:</b>
  <%= @open_defect.low %>
</p>

<p>
  <b>Project:</b>
  <%= @open_defect.project_id %>
</p>

<%= link_to 'Edit', edit_open_defect_path(@open_defect) %> |
<%= link_to 'Back', open_defects_path %>