config/routes.rb
Agilemetrics::Application.routes.draw do
  devise_for :users

  resources :open_defects

  resources :projects do
    resources :open_defects
  end

  resources :teams do
    resources :sprints
    resources :projects
  end

  match 'averages' => 'teams#averages', :as => "team_averages"
  match 'checklist' => 'checklist#index', :as => "checklist"

  root :to => 'teams#index'

end

app/models/sprint.rb
class Sprint < ActiveRecord::Base
	validates :sprint_name, :presence => true
	validates :end_date, :presence => true
	validates :code_coverage, :numericality => { :greater_than_or_equal_to => 0 }
	validates :nr_manual_tests, :numericality => { :greater_than_or_equal_to => 0 }
	validates :nr_automated_tests, :numericality => { :greater_than_or_equal_to => 0 }

  validates :planned_velocity, :presence => true
	belongs_to :team
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  include SprintsHelper



  # GET /teams/1/sprints
  # GET /teams/1/sprints.json
  def index
    @team = Team.find(params[:team_id])
    @sprints = @team.sprints.find(:all)

    respond_to do |format|
      format.html
      format.json
    end
  end



  # GET /teams/1/sprints/1
  # GET /teams/1/spritns/1.json
  def show
  @team = Team.find(params[:team_id])
  @sprint = @team.sprints.find(params[:id])
  @summary_sprint = @sprint
  @first_sprint = @team.sprints.find(:first)
  @last_sprint = @team.sprints.find(:last)
  @linear_regression = get_linear_regression_actual_velocity(@team.sprints, @last_sprint)
  @averages_set = last_n_sprints_inclusive(@team.sprints, @summary_sprint, 6)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sprint }
    end
  end



  # GET /teams/1/sprints/new
  # GET /teams/1/sprints/new.json
  def new
    @team = Team.find(params[:team_id])
    @previous_sprint = @team.sprints.find(:last)
    @sprint = @team.sprints.new

    # guess the sprint name and end date
    t = Time.now
    @sprint.sprint_name = t.strftime "%Y.%m.%d"
    @sprint.end_date = t.strftime "%Y-%m-%d"
    # pre-populate some values from the previous sprint
    if @previous_sprint != nil
      @sprint.team_size = @previous_sprint.team_size if @previous_sprint.team_size != nil
      @sprint.working_days = @previous_sprint.working_days if @previous_sprint.working_days != nil
      @sprint.pto_days = @previous_sprint.pto_days if @previous_sprint.pto_days != nil
      # guess the planned velocity using the actual velocity from the prior sprint
      @sprint.planned_velocity = @previous_sprint.actual_velocity if @previous_sprint.actual_velocity != nil

      @sprint.code_coverage = @previous_sprint.code_coverage if @previous_sprint.code_coverage != nil
      @sprint.nr_manual_tests = @previous_sprint.nr_manual_tests if @previous_sprint.nr_manual_tests != nil
      @sprint.nr_automated_tests = @previous_sprint.nr_automated_tests if @previous_sprint.nr_automated_tests != nil
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team }
    end
  end



  # GET /teams/1/sprints/1/edit
  def edit
    @team = Team.find(params[:team_id])
    @sprint = @team.sprints.find(params[:id])
  end

  def create
    @team = Team.find(params[:team_id])
    @sprint = @team.sprints.create(params[:sprint])
    redirect_to team_path(@team)
  end



  # PUT /teams/1/sprints/1
  # PUT /teams/1/sprints/1.json
  def update
    @team = Team.find(params[:team_id])
    @sprint = @team.sprints.find(params[:id])

    respond_to do |format|
      if @sprint.update_attributes(params[:sprint])
        format.html { redirect_to [@sprint.team, @sprint], notice: 'Sprint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @team = Team.find(params[:team_id])
    @sprint = @team.sprints.find(params[:id])
    @sprint.destroy
    redirect_to team_path(@team)
  end
end

app/helpers/sprints_helper.rb
require 'linearregression'
require 'enumextensions'

module SprintsHelper
	def man_days(sprint)
		team_size = sprint.team_size != nil ? sprint.team_size : 0
		working_days = sprint.working_days != nil ? sprint.working_days : 0
		pto_days = sprint.pto_days != nil ? sprint.pto_days : 0
		days = team_size * working_days - pto_days
		days
	end

	def points_per_person_day(sprint)
		man_days_denominator = man_days(sprint)
		metric = 0
		if man_days_denominator != 0
			metric = sprint.actual_velocity / man_days_denominator
		end
		metric
	end

	def get_linear_regression_actual_velocity(sprints, sprint)
		previous_sprints = sprints.select { |s| s.sprint_name < sprint.sprint_name && sprint_is_complete?(s) }
		previous_sprints = previous_sprints.last(10)

		actual_velocities = []
		if previous_sprints != nil && previous_sprints.length > 0
			actual_velocities = previous_sprints.map { |sprint| sprint.actual_velocity }
		end

		linear_regression = LinearRegression.new actual_velocities
		return linear_regression
	end

	def next_velocity_in_trend(linear_regression)
		rate = linear_regression.slope.round(1)
		reate = 0 if rate == 0
		# if the growth rate (slope) is better than 0 then give
		# the target to the next in the trend
		if rate >= 0
			linear_regression.next.ceil
		else
			# if the growth rate is negative, find out what
			# is needed to correct the behavior and stabilize at 0
			linear_regression.stabilize_over_n_values(10).ceil
		end
	end

	def velocity_growth(linear_regression)
		rate = linear_regression.slope.round(1)
		prefix = ""
		prefix = "+" if rate > 0
		# get rid of the - sign when the unrounded number was negative
		rate = 0 if rate == 0
		growth = ""
		growth = pluralize "%s%s" % [ prefix, rate ], "pt" if !rate.to_f.nan?
		growth
	end

	def maintain_target(sprints, sprint)
		# Get the previous sprints
		previous_sprints = sprints.select { |s| s.sprint_name < sprint.sprint_name && sprint_is_complete?(s) }
		previous_sprints = previous_sprints.last(6)

		# find the maximum points per day over the previous sprints
		pts_per_person_day_array = previous_sprints.map { |s| points_per_person_day(s) }
		pts_per_person_day_array.sort!
		max_pts = pts_per_person_day_array.pop

		# pts per person day of previous sprint * man days of current sprint
		target = max_pts * man_days(sprint) if max_pts != nil && sprint != nil
		if target != nil
			target.round(0)
		else
			0
		end
	end

	def effective_team_size(sprint)
		# make sure we have values
		sprint.team_size = sprint.team_size ? sprint.team_size : 0
		sprint.working_days = sprint.working_days ? sprint.working_days : 0
		sprint.pto_days = sprint.pto_days ? sprint.pto_days : 0

		# get man days first
		the_man_days = man_days(sprint)
		week_days = sprint.team.sprint_weeks * 5

		# calculate team size
		team_size = the_man_days / week_days
		team_size.round(1)
	end

	def last_n_sprints(sprints, max_nr)
		complete_sprints = sprints.select { |sprint| sprint_is_complete?(sprint) }
		complete_sprints.last max_nr
	end

	def last_n_sprints_inclusive(sprints, current_sprint, n)
		# find the current sprint
		idx = sprints.index { |sprint| sprint.sprint_name == current_sprint.sprint_name }
		if idx == nil
			return []
		end
		# get the set of the last n sprints
		set = sprints[0, idx+1].last(n)
		# get only those that are complete
		set = last_n_sprints(set, n)
	end

	def last_complete_sprint(sprints)
		completed = nil
		sprints.reverse_each do |sprint|
			if sprint_is_complete?(sprint)
				completed = sprint
				break
			end
		end
		completed
	end

  ## added check for actual_velocity != 0 to prevent errors in display
	def sprint_is_complete?(sprint)
		!sprint.sprint_name.blank? && sprint.sprint_name != nil &&
		!sprint.end_date.blank? && sprint.end_date != nil &&
		!sprint.team_size.blank? && sprint.team_size != nil &&
		!sprint.working_days.blank? && sprint.working_days != nil &&
		!sprint.pto_days.blank? && sprint.pto_days != nil &&
		!sprint.planned_velocity.blank? && sprint.planned_velocity != nil &&
		!sprint.actual_velocity.blank? && sprint.actual_velocity != nil && sprint.actual_velocity != 0 &&
		!sprint.adopted_points.blank? && sprint.adopted_points != nil &&
		!sprint.unplanned_points.blank? && sprint.unplanned_points != nil &&
		!sprint.found_points.blank? && sprint.found_points != nil &&
		!sprint.partial_points.blank? && sprint.partial_points != nil
	end

	def committed_velocity(sprint)
		found = sprint.found_points > 0 ? sprint.found_points : 0
		velocity = sprint.planned_velocity + sprint.adopted_points + sprint.unplanned_points + found
		velocity
	end

	def capacity(sprint)
		capacity = sprint.actual_velocity + sprint.partial_points
		capacity
	end

	def focus_factor(sprint)
    if  sprint.actual_velocity == 0 or sprint.actual_velocity.nan?
      return 0
    end

		focus_factor = sprint.actual_velocity / capacity(sprint)
		# Present it as a whole number instead of a decimal
		focus_factor.round(2) * 100
	end

	def commitment_accuracy(sprint)
		accuracy = sprint.actual_velocity / committed_velocity(sprint)
		accuracy.round(2) * 100
	end

	def estimation_accuracy(sprint)
		accuracy = 1 - (sprint.found_points.abs / committed_velocity(sprint))
		accuracy.round(2) * 100
	end

	def unplanned_work_percent(sprint)
		unplanned = sprint.unplanned_points / sprint.planned_velocity
		unplanned.round(2) * 100
	end

	def velocity_efficiency(sprint, first_sprint)
		pts_per_person_day = points_per_person_day(sprint)
		if first_sprint != nil
			orig_pts_per_person_day = points_per_person_day(first_sprint)
			if orig_pts_per_person_day != 0
				efficiency = pts_per_person_day / orig_pts_per_person_day
				efficiency.round(2)
			else
				0
			end
		end
	end

	def rolling_average_velocity(sprints, current_sprint, n)
		set = last_n_sprints_inclusive(sprints, current_sprint, n)
		average_velocity(set)
	end

	def average_velocity(set)
		values = set.map { |s| s.actual_velocity }
		if values.length > 0
			statsArray = StatisticalArray.new(values)
			statsArray.average.round(1)
		else
			0
		end
	end

	def average_capacity(set)
		values = set.map { |s| capacity(s) }
		if values.length > 0
			statsArray = StatisticalArray.new(values)
			statsArray.average.round(0)
		else
			0
		end
	end

	def average_focus_factor(set)
    values = set.map { |s| focus_factor(s) }
		if values.length > 0
			statsArray = StatisticalArray.new(values)
			statsArray.average.round(0)
		else
			0
		end
	end

	def average_commitment_accuracy(set)
		values = set.map { |s| commitment_accuracy(s) }
		if values.length > 0
			statsArray = StatisticalArray.new(values)
			statsArray.average.round(0)
		else
			0
		end
	end

	def average_estimation_accuracy(set)
		values = set.map { |s| estimation_accuracy(s) }
		if values.length > 0
			statsArray = StatisticalArray.new(values)
			statsArray.average.round(0)
		else
			0
		end
	end

	def average_unplanned_work(set)
		values = set.map { |s| unplanned_work_percent(s) }
		if values.length > 0
			statsArray = StatisticalArray.new(values)
			statsArray.average.round(0)
		else
			0
		end
	end

	def average_velocity_efficiency(set, first_sprint)
		values = set.map { |s| velocity_efficiency(s, first_sprint) }
		if values.length > 0
			statsArray = StatisticalArray.new(values)
			statsArray.average.round(2)
		else
			0
		end
	end

	def velocity_index(sprint, first_sprint)
		idx = sprint.actual_velocity / first_sprint.actual_velocity
		idx.round(2)
	end

	def confidence_interval(set)
		values = set.map {|s| s.actual_velocity }
		interval = "-"
		if values.length > 5
			statsArray = StatisticalArray.new(values)
			interval = "%d - %d" % [ statsArray.confidence_interval_low, statsArray.confidence_interval_high ]
		end
		return interval
	end
end

app/views/sprints/_form.html.erb
<%= form_for([@sprint.team, @sprint]) do |f| %>
  <% if @sprint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team.errors.count, "error") %> prohibited this sprint from being saved:</h2>

      <ul>
      <% @sprint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%= render :partial => "sprints/tooltipjs" %>
	<h2>Sprint Info</h2>

  <div class="field">
    <%= f.label :sprint_name %>
    <%= f.text_field :sprint_name %>
	Tip: Use format yyyy.mm.dd for easy sorting
  </div>
  <div class="field">
    <%= f.label :end_date %>
    <%= f.text_field :end_date %>
	format: yyyy-mm-dd
  </div>
  <div class="field">
    <%= f.label :team_size %>
    <%= f.text_field :team_size %>
	<a rel="tooltip" class="nolink circleButton" title="<%= render "sprints/tipteamsize" %>">?</a>
  </div>
  <div class="field">
    <%= f.label :working_days %>
    <%= f.text_field :working_days %>
	<a rel="tooltip" class="nolink circleButton" title="<%= render "sprints/tipworkingdays" %>">?</a>
  </div>
  <div class="field">
    <%= f.label "Out of office days" %>
    <%= f.text_field :pto_days %>
	<a rel="tooltip" class="nolink circleButton" title="<%= render "sprints/tipptodays" %>">?</a>
  </div>

	<h2>Actuals</h2>

  <div class="field" style="width: 100%">
	<%= f.label :planned_velocity %>
    <%= f.text_field :planned_velocity %>
	<a rel="tooltip" class="nolink circleButton" title="<%= render "sprints/tipplanned" %>">?</a>
  </div>
  <div class="field">
    <%= f.label :actual_velocity %>
    <%= f.text_field :actual_velocity %>
	<a rel="tooltip" class="nolink circleButton" title="<%= render "sprints/tipactualvelocity" %>">?</a>
  </div>
  <div class="field">
    <%= f.label :adopted_points %>
    <%= f.text_field :adopted_points %>
	<a rel="tooltip" class="nolink circleButton" title="<%= render "sprints/tipadopted" %>">?</a>
  </div>
  <div class="field">
    <%= f.label :unplanned_points %>
    <%= f.text_field :unplanned_points %>
	<a rel="tooltip" class="nolink circleButton" title="<%= render "sprints/tipunplanned" %>">?</a>
  </div>
  <div class="field">
    <%= f.label :found_points %>
    <%= f.text_field :found_points %>
	<a rel="tooltip" class="nolink circleButton" title="<%= render "sprints/tipfound" %>">?</a>
  </div>
  <div class="field">
    <%= f.label :partial_points %>
    <%= f.text_field :partial_points %>
	<a rel="tooltip" class="nolink circleButton" title="<%= render "sprints/tippartial" %>">?</a>
  </div>
	<h2>Tests</h2>

  <div class="field">
    <%= f.label :code_coverage %>
    <%= f.number_field :code_coverage, :max => 100, :step => 0.1 %>
	e.g. 33.5 means 33.5%
  </div>

  <div class="field">
    <%= f.label "Number of Manual Tests" %>
    <%= f.number_field :nr_manual_tests, :min => 0 %>
  </div>

  <div class="field">
    <%= f.label "Number of Automated Tests" %>
    <%= f.number_field :nr_automated_tests, :min => 0 %>
  </div>

  <div class="field">
    <%= f.label :note %>
    <%= f.text_area :note %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", :class => 'button large green' %>
  </div>
<% end %>

app/views/sprints/_sprint.html.erb
	<tr>
	<td><%= link_to sprint.sprint_name, team_sprint_path(sprint.team, sprint) %></td>
	<td><%= sprint.end_date %></td>
	<td class="alignNumber"><%= sprint.team_size %></td>
	<td class="alignNumber"><%= sprint.working_days %></td>
	<td class="alignNumber"><%= sprint.pto_days %></td>
	<td class="alignNumber effectiveTeamSize"><%= effective_team_size(sprint) %></td>

	<td class="alignNumber"><%= sprint.planned_velocity %></td>
	<td class="alignNumber"><%= sprint.actual_velocity %></td>
	<td class="alignNumber"><%= sprint.adopted_points %></td>
	<td class="alignNumber"><%= sprint.unplanned_points %></td>
	<td class="alignNumber"><%= sprint.found_points %></td>
	<td class="alignNumber"><%= sprint.partial_points %></td>

	<td class="alignNumber"><%= sprint.code_coverage %></td>
	<td class="alignNumber"><%= sprint.nr_manual_tests %></td>
	<td class="alignNumber"><%= sprint.nr_automated_tests %></td>

    <td<%= ' colspan="3"' if !is_username_an_owner_of_team?(current_user.login, @team) -%> style="text-align:center"><%= link_to 'show', team_sprint_path(sprint.team, sprint) %></td>
	<% if is_username_an_owner_of_team?(current_user.login, @team) -%>
    	<td style="text-align:center"><%= link_to 'edit', edit_team_sprint_path(sprint.team, sprint) %></td>
		<td style="text-align:center"><%= link_to "delete", [sprint.team, sprint], :confirm => "Are you sure you want to delete #{sprint.sprint_name}?", :method => :delete %></td>
	<% end -%>
	</tr>

app/views/sprints/_tipadopted.html.erb
Adopted Points:<br/>Total additonal story points (whether done or not) pulled into the sprint by the team after the sprint commences. Do not include story points that were evenly swapped out by the product owner.

app/views/sprints/_tipcommitmentaccuracy.html.erb
Commitment Accuracy:<br/>The ratio of Actual Velocity to the team's Committed Velocity.

app/views/sprints/_tipcommittedvelocity.html.erb
Committed Velocity:<br/>This is the sum of planned work, adopted work, found work, and unplanned work for the sprint.

app/views/sprints/_tipconfidence.html.erb
90% Velocity Confidence Interval:<br/>The low and high velocity values that express a 90% confidence interval around the mean (average velocity). In other words, based on the team's history, there is a 90% chance that their velocity will fall between these two numbers. In roadmap/release planning, product owners can use the numbers to determine the likelihood of reaching a certain point in the product backlog.

app/views/sprints/_tipfound.html.erb
Found Points:<br/>The total story points that were discovered (done or not) by the team while working on the sprint backlog.  This is used to calculate estimation accuracy.

app/views/sprints/_tippartial.html.erb
Partial Points:<br/>The sum of points started on stories, but whose stories were not done at the end of the sprint.

app/views/sprints/_tipplanned.html.erb
Planned Velocity:<br/> The sum of all story points committed to at the beginning of the sprint.

app/views/sprints/_tipptodays.html.erb
PTO/OOO Days:<br/>The number of vacation or OOO (out of office) days. Do not try to account for meetings and other normal overhead. That will be reflected in the normal velocity calculations.

app/views/sprints/_tipteamsize.html.erb
Team Size:<br/>The number of team members.

app/views/sprints/_tipworkingdays.html.erb
Working Days:<br/>Enter the actual number of working days in the sprint. Use half-day increments. Do not include holidays or other significant time-off events for the entire team (a company or team party). Do not subtract for normal team meetings and other normal overhead.<br/><br/>Example: There are normally 10 days in a 2 week sprint, but team has 1 company holiday during that time and a 1/2 day department activity. You should enter 8.5 (10 - 1.5 = 8.5).

app/views/sprints/index.html.erb
<h1><%= @team.name %></h1>
<%= link_to "back to teams", teams_path %>
<%= link_to "back to the #{@team.name} team", team_path(@team.id) %>

<h2>sprints</h2>

<p>Tip: sprints are ordered by name with the most recent at top of the list below. Name your sprints to fit alphabetically in the list.</p>

<% if is_username_an_owner_of_team?(current_user.login, @team) -%>
<p><%= link_to "add a sprint", new_team_sprint_path(@team), :class => "button"  %></p>
<% end -%>

<%= render "teams/sprintlist" %>

app/views/sprints/show.html.erb
<h1><%= @sprint.team.name %> | <%= @sprint.sprint_name %></h1>

<% if is_username_an_owner_of_team?(current_user.login, @sprint.team) -%>
	<%= link_to "edit sprint #{@sprint.sprint_name}", edit_team_sprint_path(@sprint.team, @sprint) %> |
<% end -%>
<%= link_to "back to the #{@sprint.team.name} team", team_path(@sprint.team) %>

<div class="clear"></div>
<% if sprint_is_complete?(@sprint) %>
<div class="column">
<h2>Summary</h2>
<%= render "sprints/summary" %>
</div>
<% end %>

<div class="column">
<h2>Sprint Info</h2>
<table>
<tbody>
<tr>
<td>End date</td>
<td><%= @sprint.end_date %></td>
</tr>

<tr>
<td>Team size</td>
<td class="alignNumber"><%= @sprint.team_size %></td>
</tr>

<tr>
<td>Working days</td>
<td class="alignNumber"><%= @sprint.working_days %></td>
</tr>

<tr>
<td>PTO/OOO days</td>
<td class="alignNumber"><%= @sprint.pto_days %></td>
</tr>

<tr>
<td>Effective team size</td>
<td class="alignNumber"><%= effective_team_size(@sprint) %></td>
</tr>
</tbody>
</table>
</div>

<div class="column">
<h2>Actuals</h2>
<table>
<tbody>
<tr>
<td>Planned velocity</td>
<td class="alignNumber"><%= @sprint.planned_velocity %></td>
</tr>

<tr>
<td>Actual velocity</td>
<td class="alignNumber"><%= @sprint.actual_velocity %></td>
</tr>

<tr>
<td>Adopted points</td>
<td class="alignNumber"><%= @sprint.adopted_points %></td>
</tr>

<tr>
<td>Unplanned points</td>
<td class="alignNumber"><%= @sprint.unplanned_points %></td>
</tr>

<tr>
<td>Found points</td>
<td class="alignNumber"><%= @sprint.found_points %></td>
</tr>

<tr>
<td>Partial points</td>
<td class="alignNumber"><%= @sprint.partial_points %></td>
</tr>
</tbody>
</table>
</div>

<div class="column">
<h2>Tests</h2>
<table>
<tbody>
<tr>
<td>Code coverage</td>
<td class="alignNumber"><%= !@sprint.code_coverage.blank? ? "%s%%" % @sprint.code_coverage : "0%"  %></td>
</tr>

<tr>
<td>Manual Tests</td>
<td class="alignNumber"><%= @sprint.nr_manual_tests %></td>
</tr>

<tr>
<td>Automated Tests</td>
<td class="alignNumber"><%= @sprint.nr_automated_tests %></td>
</tr>
</tbody>
</table>
</div>

<div class="clear"></div>

<% if @sprint.note != nil && !@sprint.note.blank? %>
<h2>Notes</h2>
<p><%= @sprint.note %>
<% end %>