config/routes.rb
Agilemetrics::Application.routes.draw do
  devise_for :users

  resources :open_defects

  resources :projects do
    resources :open_defects
  end

  resources :teams do
    resources :sprints
    resources :projects
  end

  match 'averages' => 'teams#averages', :as => "team_averages"
  match 'checklist' => 'checklist#index', :as => "checklist"

  root :to => 'teams#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, :presence => true
	validates :tfs_path, :presence => true
	validates :team_id, :presence => true

	belongs_to :team
	has_many :open_defects
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include SprintsHelper
  include OpenDefectsHelper



  # GET /projects
  # GET /projects.json
  def index
    if params[:team_id]
      @team = Team.find(params[:team_id])
      @projects = Project.where(:team_id => @team.id)
    else
      @projects = Project.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end



  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @team = Team.find(@project.team_id)
    @all_open_defects = OpenDefect.where(:project_id => @project.id)
    @current_open_defects = OpenDefect.where(:project_id => @project.id).order("week_ending DESC").limit(1).first  #is this correct?

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end



  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    @teams = Team.where(:is_archived => false).order("name")

    if params[:team_id]
      @team = Team.find(params[:team_id])
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end



  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    @teams = Team.where(:is_archived => false)
  end



  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end



  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    @teams = Team.where(:is_archived => false)

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  # determines if the team for a project is the one selected (for the team dropdown)
  def selected?(team)
    if not team.nil?
	   return team
    end
  end

end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>

    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tfs_path %>
    <br/>
    <%= f.text_field :tfs_path %>
        <i>e.g. <b>\Ancestry\TFSPath</b></i>
  </div>
  <div class="field">
    <%= f.label 'Team' %><br />
    <% team = Team.find(params[:team_id]) %>
    <%= f.collection_select :team_id, @teams , :id, :name, :prompt => true, :selected => selected?(team.id) %>
  </div>

  <div class="actions">
    <%= f.submit "save", :class => "button" %>
  </div>
<% end %>

app/views/projects/_opendefectslist.html.erb
<table class="open_defects">
  
  <thead>
    <tr>
      <th class="openDefectsInfo" colspan="6">Open Defects</th>
    </tr>
    <tr>
      <th>Week Ending</th>
      <th>Critical</th>
      <th>High</th>
      <th>Medium</th>
      <th>Low</th>
      <th>Total</th>
    </tr>
  </thead>

  <tbody>

  <% open_defects.each do |report| %>
  
    <tr>
      <td class="week_ending"><%= report.week_ending %></td>
      <td class="defect_count"><%= report.critical %></td>
      <td class="defect_count"><%= report.high %></td>
      <td class="defect_count"><%= report.medium %></td>
      <td class="defect_count"><%= report.low %></td>
      <td class="defect_count defect_total"><%= report.critical + report.high + report.medium + report.low %></td>
    </tr>

  <% end %>

  </tbody>
</table>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @project %> | <%= link_to 'All Projects', projects_path %>

<h2> Open Defects </h2>

app/views/projects/index.html.erb
<h1>Projects</h1>

<% if @team %>
  <h2> for <%= link_to @team.name, team_path(@team) %> team </h2>
<% else %>
  <h2> for all teams</th>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th>TFS path</th>
    <th>Team</th>
    <th>Actions</th>
  </tr>

<% @projects.each do |project| %>

  <tr>
    <td><%= link_to project.name, project %></td>
    <td><%= project.tfs_path %></td>
    <td><%= project.team.name %></td>
    <td>
      <% if is_username_an_owner_of_team?(current_user.login, @team) -%>
      <%= link_to 'Edit', edit_project_path(project) %> | <%= link_to 'Delete', project, confirm: 'Are you sure?', method: :delete %>
      <% end %>
    </td>
  </tr>

<% end %>

</table>

<br />

<% if is_username_an_owner_of_team?(current_user.login, @team) -%>
  <p>You can add projects from TFS to track open defects</p> 

  <%= link_to 'add a project', new_project_path, :team => @team, :class => "button" %>
<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"></p>
<h1> Project </h1>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Tfs path:</b>
  <%= @project.tfs_path %>
</p>

<p>
  <b>Team:</b>
  <%= link_to @team.name, team_path(@team) %>
</p>


<h2> Open Defects </h2>
<%= render "projects/opendefectslist", :open_defects => current_open_defects_for_project(@project) %>
<p>
<%= link_to "open defects history", project_open_defects_path(@project) %>
</p>
  
<% if is_username_an_owner_of_team?(current_user.login, @team) -%>
  <%= link_to 'Edit Project', edit_project_path(@project) %> |
<% end %>

<%= link_to 'All Projects', projects_path %>